from enum import Enum, auto


class WeaponId(Enum):
    CLUB = auto()
    DAGGER = auto()
    GREATCLUB = auto()
    HANDAXE = auto()
    JAVELIN = auto()
    LIGHT_HAMMER = auto()
    MACE = auto()
    QUARTERSTAFF = auto()
    SICKLE = auto()
    SPEAR = auto()
    LIGHT_CROSSBOW = auto()
    DART = auto()
    SHORTBOW = auto()
    SLING = auto()
    BATTLEAXE = auto()
    FLAIL = auto()
    GLAIVE = auto()
    GREATAXE = auto()
    HALBERD = auto()
    LANCE = auto()
    LONGSWORD = auto()
    MAUL = auto()
    MORNINGSTAR = auto()
    PIKE = auto()
    RAPIER = auto()
    SCIMITAR = auto()
    SHORTSWORD = auto()
    TRIDENT = auto()
    WAR_PICK = auto()
    WARHAMMER = auto()
    WHIP = auto()
    BLOWGUN = auto()
    HAND_CROSSBOW = auto()
    HEAVY_CROSSBOW = auto()
    LONGBOW = auto()
    NET = auto()
    UNARMED = auto()
    GREATSWORD = auto()
